host_specific_tasks:
  csbingao@clnode316.clemson.cloudlab.us:
    range: "0-150"
  csbingao@clnode289.clemson.cloudlab.us:
    range: "151-301"
  csbingao@clnode310.clemson.cloudlab.us:
    range: "302-452"
  csbingao@clnode314.clemson.cloudlab.us:
    range: "453-603"
  csbingao@clnode292.clemson.cloudlab.us:
    range: "604-754"
  csbingao@clnode290.clemson.cloudlab.us:
    range: "755-905"
  csbingao@clnode291.clemson.cloudlab.us:
    range: "906-1056"
  csbingao@clnode305.clemson.cloudlab.us:
    range: "1057-1207"
  csbingao@clnode296.clemson.cloudlab.us:
    range: "1208-1358"
  csbingao@clnode298.clemson.cloudlab.us:
    range: "1359-1509"
  csbingao@clnode308.clemson.cloudlab.us:
    range: "1510-1660"
  csbingao@clnode299.clemson.cloudlab.us:
    range: "1661-1811"
  csbingao@clnode293.clemson.cloudlab.us:
    range: "1812-1962"
  csbingao@clnode286.clemson.cloudlab.us:
    range: "1963-2113"
  csbingao@clnode315.clemson.cloudlab.us:
    range: "2114-2261"
